check escaper for the key barrier
paypal/paypalhttp_java pull request #9
Opened 2021-06-19 19:51 UTC by voylex

2021-06-21 21:59 UTC, voylex commented
the StringEscapeUtil.unescape method seems not working for the above specific case.
input:
"test \ \ \", " 

output from the escape util:
"test ", "

expected:
"test \\\", "

the back slash will not stay if we are using unescape method

2021-06-22 22:39 UTC, voylex commented
Again, tried with the StringEscapeUtil.unescape(), it seems not working, the json decoder will be confused about the first double quote it gets.

and to be clear:
input is 
\ "test \ \ \ ", \ " 

current fix will return 

\"test \ \ \ ", \" -> looks like -> "test \", " to the api caller

with the jsonescaper, it will return as
\"test \", \" 
from the json string perspective, it has to stop and process this part \"test \"

2021-06-25 03:53 UTC, p1ngle requested changes

2021-06-25 23:37 UTC, voylex commented
@p1ngle  hey Peng, just resolve the comments, can you check now? thanks !

2021-06-26 03:21 UTC, p1ngle requested changes
One minor type

2021-06-26 03:21 UTC, p1ngle commented on paypalhttp/src/main/java/com/paypal/http/serializer/Json.java
> +	private static final char KEY_ESCAPER = 92; // '/' the backslash value
backslash is `\`

2021-06-28 00:56 UTC, voylex commented on paypalhttp/src/main/java/com/paypal/http/serializer/Json.java
> +	private static final char KEY_ESCAPER = 92; // '/' the backslash value
resolved

2021-06-28 05:04 UTC, p1ngle approved these changes
LGTM

2021-06-28 17:15 UTC, merged